name = "wardyati-servers"
main = "src/index.js"
compatibility_date = "2024-01-01"

[durable_objects]
bindings = [
  { name = "SNIPE_OBJECT", class_name = "SnipeObject" }
]

[[migrations]]
tag = "v1"
new_sqlite_classes = ["SnipeObject"]
